spring.application.name=mall
# --- JPA Settings ---
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# --- MySQL Settings ---
spring.datasource.username=root

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

# --- Init Settings ---
spring.sql.init.mode=never
#spring.jpa.defer-datasource-initialization=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# --- this for push message key ---

vapid.public=BFArFFwk06l4X_tQ-brP3nEFpgDp2MNlK75atdO5aw-WWdF5pNq6SrG60pfWcM1r5fD-VR93OJeu1mhCmcRGdAg
vapid.private=jh7hHk6kXurOEMF32844xKBfIaAAllMaYzwMvHu4GvQ
