spring.application.name=mall
server.port=8081

# ========== MAIN DATABASE ==========
spring.datasource.main.jdbc-url=jdbc:mysql://localhost:3306/database
spring.datasource.main.username=root
spring.datasource.main.password=root
spring.datasource.main.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== AUDIT DATABASE ==========
spring.datasource.audit.jdbc-url=jdbc:mysql://localhost:3306/auditlog
spring.datasource.audit.username=root
spring.datasource.audit.password=root
spring.datasource.audit.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Data Initialization Settings ---
spring.sql.init.mode=never

#--------------- available file size -------------------
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# --- this for push message key ---
vapid.public=BCRl3b3l4QjY-81k1ZuLIJ24yPHBzlBbzdKORS0rpuKTlXJHTgMjFB31V3zI0A3u_abH6Eoy6ClkRs_kHBBNhKA
vapid.private=FEi44hWz90SCM8Q880MM6NVZvRD3zvABFkAenir4zM4